import { cn } from '@angular-ai-kit/utils';
import { isPlatformBrowser } from '@angular/common';
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  PLATFORM_ID,
  ViewEncapsulation,
  computed,
  effect,
  inject,
  input,
  output,
  viewChild,
} from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { MarkdownService } from '../../../services/markdown.service';

/**
 * Markdown Renderer Component
 *
 * Renders markdown content with syntax highlighting for code blocks.
 * Wraps the MarkdownService and provides a clean component interface.
 *
 * Features:
 * - Full GFM (GitHub Flavored Markdown) support
 * - Code blocks with syntax highlighting
 * - Copy buttons on code blocks
 * - Sanitized HTML output
 *
 * @example
 * ```html
 * <ai-markdown-renderer
 *   [content]="markdownString"
 *   (codeBlockCopy)="handleCopy($event)"
 * />
 * ```
 */
@Component({
  selector: 'ai-markdown-renderer',
  templateUrl: './markdown-renderer.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'ai-markdown-renderer block',
    '[class]': 'hostClasses()',
  },
})
export class MarkdownRendererComponent implements AfterViewInit {
  private platformId = inject(PLATFORM_ID);
  private markdownService = inject(MarkdownService);
  private sanitizer = inject(DomSanitizer);

  // View children
  private contentRef = viewChild<ElementRef<HTMLDivElement>>('contentArea');

  // ==========================================
  // Inputs
  // ==========================================

  /** The markdown content to render */
  content = input.required<string>();

  /** Custom CSS classes */
  customClasses = input<string>('');

  // ==========================================
  // Outputs
  // ==========================================

  /** Emitted when a code block's copy button is clicked */
  codeBlockCopy = output<string>();

  // ==========================================
  // Computed Properties
  // ==========================================

  /** Host element classes */
  hostClasses = computed(() => cn('ai-markdown-content', this.customClasses()));

  /**
   * Rendered HTML from markdown.
   *
   * @security This uses `bypassSecurityTrustHtml` to allow interactive elements
   * in rendered code blocks. This is safe when content comes from trusted sources.
   */
  renderedHtml = computed((): SafeHtml => {
    const markdown = this.content();
    if (!markdown) return '';

    const html = this.markdownService.parse(markdown);
    return this.sanitizer.bypassSecurityTrustHtml(html);
  });

  // ==========================================
  // Lifecycle
  // ==========================================

  constructor() {
    // Re-attach copy button handlers when content changes
    effect(() => {
      // Read content to track changes
      this.content();

      if (isPlatformBrowser(this.platformId)) {
        // Use setTimeout to ensure DOM is updated
        setTimeout(() => this.attachCopyHandlers(), 0);
      }
    });
  }

  ngAfterViewInit(): void {
    this.attachCopyHandlers();
  }

  // ==========================================
  // Private Methods
  // ==========================================

  /** Attach click handlers to code block copy buttons */
  private attachCopyHandlers(): void {
    if (!isPlatformBrowser(this.platformId)) return;

    const contentEl = this.contentRef()?.nativeElement;
    if (!contentEl) return;

    // Find all copy buttons generated by the markdown renderer
    const copyButtons = contentEl.querySelectorAll<HTMLButtonElement>(
      '.ai-code-block-copy'
    );

    copyButtons.forEach((btn) => {
      // Skip if already has a handler attached
      if (btn.dataset['handlerAttached']) return;
      btn.dataset['handlerAttached'] = 'true';

      btn.addEventListener('click', () => {
        const encodedCode = btn.dataset['code'];
        if (encodedCode) {
          const code = decodeURIComponent(encodedCode);

          // Emit event
          this.codeBlockCopy.emit(code);

          // Copy to clipboard and show feedback
          navigator.clipboard.writeText(code).then(() => {
            const originalHtml = btn.innerHTML;
            btn.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"/></svg>`;
            btn.classList.add('copied');

            setTimeout(() => {
              btn.innerHTML = originalHtml;
              btn.classList.remove('copied');
            }, 2000);
          });
        }
      });
    });
  }
}
